### ISSUE TITLE
Incorrect Provider Value Requirements for HCX on VMC

### ISSUE THREAD

**Issue by uprightvinyl** [adeleporte/terraform-provider-hcx#1]
The provider cannot be used without supplying values for "hcx", "username" and "password". However, for HCX on VMC, those values are not required. I have worked around this by putting dummy values in the provider block. Is there anyway the requirement for these values can be ignored if the config is just being used for HCX on VMC?

Nice work on this provider by the way!

**Comment by adeleporte** [comment]
Hi Chris,
not sure to get your point, even if using this provider with VMC, the username and password are required (these are the credentials the provider can use once SSO and vSphere Role Mapping have been set).
However, if you want to manage only the HCX appliance (i.e vCenter/SSO/location/activation..) without managing the HCX configuration (Site Pairing/Compute Profiles...), you're right, the username/password should be optional.
I've just released a v0.2.8 which is now available.
username/password/admin_username/admin_password are now all optional.

Antoine

**Comment by uprightvinyl** [comment]
Wow, thanks for the quick response! Yes, I should have been clearer, this is to allow the HCX activation on VMC to take place in a separate phase to the configuration. Thanks again!

**Comment by uprightvinyl** [comment]
@adeleporte Just had chance to test this. It's now not asking for username/password, but the value "hcx" is still required. Would it be possible to set that property to optional as well?

**Comment by adeleporte** [comment]
Hi Chris,
The hcx value is used to specify which HCX manager you want to manage with TF. It doesn't make sense to set this value optional.
Antoine

**Comment by uprightvinyl** [comment]
In my scenario, I'm using the HCX provider to enable the HCX addon in VMC, which doesn't need this value. Which is why in my scenario it would make sense to have this as optional as well. In a subsequent phase, I'm then connecting to HCX and configuring site pairings etc. In that phase, the provider has the required configuration so it can make a connection.

Is it possible to connect to HCX without the username and password, as those _are_ optional? I would say for consistency, either all three parameters should be optional (hcx/username/password), or all of them should be mandatory.

**Comment by adeleporte** [comment]
Hi Chris,
I see your point. In my own opinion, the HCX activation should be manageable in the VMC provider, instead of the HCX provider.
Anyway, I've updated the "hcx" requirement which is now optional (the provider should generate a warning message indicating that only hcx_vmc resource is manageable). Doc is updated as well.
Antoine
