### ISSUE TITLE
hcx_network_profile doesn't support import

### ISSUE THREAD

**Issue by Lizzam** [adeleporte/terraform-provider-hcx#3]
Hi,

I'm trying to configure the default network profile that comes with a VMC SDDC labeled as "directConnectNetwork1" as we are unable to create our own network profile.

However the hcx_network_profile resource does not support terraform import currently. Can this please be supported?

Thanks

**Comment by Lizzam** [comment]
More info:

We are getting a 403 denied when trying to create a network_profile:
```
Error: status: 403, body: {
  "timestamp" : 1614650285355,
  "status" : 403,
  "error" : "Forbidden",
2021/03/02 12:58:05 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
  "message" : "Access Denied for the Requested URI /admin/hybridity/api/networkBackings",
  "path" : "/admin/hybridity/api/networkBackings"
}
```

Also, looking at your example, you are creating a network profile that depends on getting the vcenter ID from an already existing site pairing. Is this the intended order of operation? Do we need a site pairing to exist before configuring a network profile?

**Comment by adeleporte** [comment]
Hi,
v0.4.0 is just released and supports updating the default network profiles in VMC use cases.
Site Pairing is still needed for getting the vCenter ID in this release.
Please read carefully this guide:
https://registry.terraform.io/providers/adeleporte/hcx/latest/docs/guides/cloud-to-cloud for an example
and
https://registry.terraform.io/providers/adeleporte/hcx/latest/docs/resources/network_profile for reference

Antoine
